### ISSUE TITLE
GUILDS

### ISSUE THREAD

**Issue by ghost** [tkprocat/tso-nf.com#43]
guilds broken, cant delete myself (MarkG_US) from guild highlander, still shows on latest/users as in highlanders

I left GAF, nobody from that guild on loottracker, skelly83 left gaf too, couldnt remove him myself
joined highlanders, left that too, no other users
joined TC, left that too, still one person in guild on tracker so all good

need a Delete Guild option

will be joining another guild soon i expect on zeus

**Comment by tkprocat** [comment]
This should all be fixed with the new system.
