### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Notious** [tkprocat/tso-nf.com#66]
on the pricing list are mostly set to 'unknown'. Even known categories (like decoration) aren't showed after the first line.

**Comment by tkprocat** [comment]
Can be changed under Admin -> Items -> Update item.

**Comment by tkprocat** [comment]
Categories needs to be set for the remaining items.

**Comment by Notious** [comment]
Piero's Bowl of Pasta is 6 times in item list, I suppose i can remove 5 of them?

Furthermore, when in Admin --> Items : Clicking an item gives message 'Whoops, something went wrong'

**Comment by tkprocat** [comment]
Fixed
