### ISSUE TITLE
Price list

### ISSUE THREAD

**Issue by Notious** [tkprocat/tso-nf.com#67]
Imported version showing lots of value '0'

**Comment by tkprocat** [comment]
Prices are added by hand under Admin -> Prices.

**Comment by tkprocat** [comment]
We need to get as many prices added on beta before launch. The plan is to copy items and their prices over to live.

**Comment by Notious** [comment]
Not every item/resource is in the price list. Is that intended?
For example : Damascene sword

**Comment by tkprocat** [comment]
Excatly, the items are generated from items we already had registered for adventures. It is possible to add new items through admin section thou, so please do or let me know when you find items missing :)
